logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: 8080
  servlet:
    context-path: /directoryServices

spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/HHTEDDB
    username: root
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  springdoc:
    packagesToScan: com.hiberus.employee.directory.controller
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true