logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: 8080
  servlet:
    context-path: /directoryServices
spring:
  datasource:
    url: jdbc:mariadb://192.168.1.110:3306/HHTEDDB
    username: DHBRED
    password: develop
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect