logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: 8080
  servlet:
    context-path: /directoryServices
spring:
  datasource:
    url: jdbc:mariadb://192.168.1.110:3306/BDDINVENTORY
    username: DHBRED
    password: desarrollo
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show:
      sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect