logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: ERROR

server:
  port: ${PORT}
  servlet:
    context-path: /directoryServices

spring:
  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://192.168.1.110:3306/HHTEDDB
#    username: DHBRED
#    password: develop
    driver-class-name: com.mysql.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
#        dialect: org.hibernate.dialect.MariaDB103Dialect

springdoc:
  springdoc:
    packagesToScan: com.hiberus.employee.directory.controller
  api-docs:
    path: /openapi
  swagger-ui:
    path: /swagger-ui
    enabled: true
    disable-swagger-default-url: true